image: php:8

stages:
    - build
    - review
    - test
    - security
    - deploy

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

build:dependencies:
  stage: build
  image: $CI_REGISTRY/appsolute-internal/laravel-bo-api-starter:latest
  script:
      - cp .env.testing .env
      - composer config platform-check false
      - COMPOSER_CACHE_DIR=.composer composer install --prefer-dist --no-ansi --no-interaction --no-progress
  artifacts:
    paths:
      - vendor/
    expire_in: 60 mins
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .composer/
      - vendor/
  needs: []

build:assets:
  stage: build
  image: node:12
  variables:
    MIX_API_BASE_URL: "https://my-project.appsolute.dev"
  script:
      - npm ci --cache .npm --prefer-offline
      - npm run prod
  artifacts:
    paths:
      - public/css
      - public/js
      - public/fonts/font-awesome
      - public/images
    expire_in: 60 mins
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .npm/
  only:
    - develop
  needs: []

review:lint:
  stage: review
  dependencies:
    - build:dependencies
  script:
    - vendor/bin/php-cs-fixer fix --config=.php_cs.dist --dry-run --diff --using-cache=no
  needs: ["build:dependencies"]

review:stan:
  stage: review
  dependencies:
    - build:dependencies
  script:
    - vendor/bin/phpstan analyse --no-progress --memory-limit=-1
  needs: ["build:dependencies"]

review:code:
  stage: review
  dependencies:
    - build:dependencies
  script:
    - vendor/bin/rector process --config rector.php --dry-run --no-progress-bar
  needs: ["build:dependencies"]

security:sensiolabs:
  stage: security
  dependencies: []
  script:
    - curl -sL -o local-php-security-checker https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_amd64
    - chmod +x local-php-security-checker
    - ./local-php-security-checker
  needs: []

deploy:develop:
  stage: deploy
  image: $CI_REGISTRY/appsolute-internal/container-registry/deployer-php:latest
  dependencies:
    - build:assets
  script:
    - install -m 600 /dev/null ~/.ssh/id_rsa && (echo $SSH_PRIVATE_DEV_KEY | base64 -d) > ~/.ssh/id_rsa
    - dep deploy develop
  environment:
    name: development
    url: https://my-project.appsolute.dev
  only:
    - develop
